/**
 * Generated by orval 🍺
 * Do not edit manually.
 * __PROJECT__ API
 * OpenAPI spec version: 1.0.0
 */
import type {
  HealthResponseDto
} from './model.zod';

import { httpClient } from '../lib/http/client';


export const getHealthUrl = () => {




  return `/api/health`
}

export const health = async ( options?: Parameters<typeof httpClient>[1]): Promise<HealthResponseDto> => {

  return httpClient<HealthResponseDto>(getHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


