/**
 * Generated by orval 🍺
 * Do not edit manually.
 * __PROJECT__ API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const HealthResponseDto = zod.object({
  "status": zod.literal("ok"),
  "database": zod.enum(['up', 'down'])
})

export type HealthResponseDto = zod.input<typeof HealthResponseDto>;
export type HealthResponseDtoOutput = zod.output<typeof HealthResponseDto>;

