import { afterAll, describe, expect, it } from 'vitest';
import { copyFixture, edit, emptyProject, removeCopies, run, write } from './lib/testing.ts';

afterAll(removeCopies);

const MATRIX = '.metri/MATRIX.md';
const ARCHITECTURE = '.metri/ARCHITECTURE.md';
const PAGE = 'apps/app-web/src/pages/orders/orders-page.tsx';

const header = (owner: string) =>
  `/** SOURCE OF TRUTH: ${owner}.\n * WHAT: does one thing.\n * WHY: the flow needs it.\n * WHERE: called by the module.\n */\n`;

// Runs metri sot on a copy of the fixture after the change and returns the output.
function sotChanged(change: (dir: string) => void = () => {}): { status: number | null; output: string } {
  const dir = copyFixture();
  change(dir);
  const { status, lines } = run('sot', ['--root', dir]);
  return { status, output: lines.join('\n') };
}

describe('sot', { timeout: 60_000 }, () => {
  it('passa: a fixture de projeto', () => {
    expect(sotChanged()).toEqual({ status: 0, output: '' });
  });

  it('pendente: sem arquivo-fonte, e com o mapeamento pendente', () => {
    expect(run('sot', ['--root', emptyProject()]).lines).toEqual(['pendente: sem arquivo-fonte em apps/, packages/ ou src/']);
    const pending = sotChanged((dir) => {
      edit(dir, ARCHITECTURE, (source) => source.replace('# Arquitetura do projeto\n', '# Arquitetura do projeto\n\nmapeamento: pendente\n'));
      write(dir, 'src/main.ts', 'export {};\n');
    });
    expect(pending.status).toBe(0);
    expect(pending.output).toMatch(/^pendente: mapeamento: pendente/);
  });

  it('cabeçalho bem formado: WHAT, WHY e WHERE, nessa ordem e com texto', () => {
    const { status, output } = sotChanged((dir) =>
      write(dir, 'packages/core/src/money.ts', '/** SOURCE OF TRUTH: Money.\n * WHAT: amount in cents.\n * WHERE: TODO\n */\nexport class Money {}\n'),
    );
    expect(status).toBe(1);
    expect(output).toContain('packages/core/src/money.ts:1: cabeçalho: falta WHY: na linha 3');
    expect(output).toContain('packages/core/src/money.ts:1: cabeçalho: falta WHERE: na linha 4');
  });

  it('cabeçalho: depois dos imports, logo acima do export (decorator vale)', () => {
    const before = sotChanged((dir) =>
      write(dir, 'packages/core/src/money.ts', `${header('Money')}import { x } from './x';\n\nexport class Money {}\n`),
    );
    expect(before.output).toContain('cabeçalho: fica depois dos imports');
    expect(before.output).toContain('cabeçalho: fica logo acima do export que o arquivo possui');
    const decorated = sotChanged((dir) =>
      write(dir, 'apps/app-api/src/order.controller.ts', `import { Controller } from '@nestjs/common';\n\n${header('OrderController')}@Controller('orders')\nexport class OrderController {}\n`),
    );
    expect(decorated).toEqual({ status: 0, output: '' });
    const lineComment = sotChanged((dir) =>
      write(dir, 'packages/core/src/money.ts', `// SOURCE OF TRUTH: Money.\n${header('Money')}export class Money {}\n`),
    );
    expect(lineComment.output).toContain('cabeçalho: SOURCE OF TRUTH vai num comentário /** ... */');
  });

  it('todo arquivo-fonte tem cabeçalho, menos gerado, barrel, spec, e2e e apoio de teste', () => {
    const missing = sotChanged((dir) => write(dir, 'packages/core/src/money.ts', 'export class Money {}\n'));
    expect(missing.status).toBe(1);
    expect(missing.output).toContain('packages/core/src/money.ts:1: cabeçalho: arquivo-fonte sem SOURCE OF TRUTH');
    const exempt = sotChanged((dir) => {
      write(dir, 'apps/app-web/src/api/orders.ts', '/**\n * Generated by orval. Do not edit manually.\n */\nexport const x = 1;\n');
      write(dir, 'packages/db/generated/client.ts', 'export const client = {};\n');
      write(dir, 'packages/ui/src/components/ui/button.tsx', 'export function Button() {\n  return null;\n}\n');
      write(dir, 'packages/core/src/index.ts', "// o mapa do pacote\nexport { Money } from './money';\nexport * from './either';\nexport type { Id } from './id';\n");
      write(dir, 'packages/core/src/money.spec.ts', "import { it } from 'vitest';\nit('x', () => {});\n");
      write(dir, 'apps/app-api/src/orders.e2e-spec.ts', 'export {};\n');
      write(dir, 'apps/app-web/e2e/orders/list.e2e.ts', 'export {};\n');
      write(dir, 'apps/app-web/e2e/evidence.ts', 'export function evidencePath() {}\n');
      write(dir, 'apps/app-api/test/setup-e2e.ts', 'export {};\n');
      write(dir, 'apps/app-web/src/vite-env.d.ts', '/// <reference types="vite/client" />\n');
    });
    expect(exempt).toEqual({ status: 0, output: '' });
    const notBarrel = sotChanged((dir) => write(dir, 'apps/app-web/src/app/index.tsx', 'export function App() {\n  return null;\n}\n'));
    expect(notBarrel.output).toContain('apps/app-web/src/app/index.tsx:1: cabeçalho: arquivo-fonte sem SOURCE OF TRUTH');
  });

  it('sot: cada símbolo está declarado e tem o cabeçalho que o nomeia', () => {
    const noHeader = sotChanged((dir) => edit(dir, MATRIX, (source) => source.replace('sot: [OrdersPage]', 'sot: [OrdersPage, OrderList]')));
    expect(noHeader.status).toBe(1);
    expect(noHeader.output).toContain('.metri/MATRIX.md:7: sot de S1: nenhum cabeçalho SOURCE OF TRUTH nomeia OrderList');
    const undeclared = sotChanged((dir) => {
      edit(dir, MATRIX, (source) => source.replace('sot: [OrdersPage]', 'sot: [OrdersPage, OrderList]'));
      edit(dir, PAGE, (source) => source.replace('SOURCE OF TRUTH: OrdersPage.', 'SOURCE OF TRUTH: OrdersPage, OrderList.'));
    });
    expect(undeclared.output).toContain(`sot de S1: OrderList está no cabeçalho de ${PAGE}, mas nenhum arquivo o declara`);
  });

  it('slice done: tem sot e não guarda o contract', () => {
    const withContract = sotChanged((dir) => edit(dir, MATRIX, (source) => source.replace('horizon: now · blocked_by: [S1]', 'status: done · sot: [OrdersPage]')));
    expect(withContract.status).toBe(1);
    expect(withContract.output).toContain('S2: slice done guarda o bloco contract');
    const noSot = sotChanged((dir) => edit(dir, MATRIX, (source) => source.replace('horizon: now · sot: [OrdersPage]', 'status: done')));
    expect(noSot.output).toContain('S1: slice done sem sot: [<símbolo>]');
    const done = sotChanged((dir) => edit(dir, MATRIX, (source) => source.replace('horizon: now · sot: [OrdersPage]', 'status: done · sot: [OrdersPage]')));
    expect(done).toEqual({ status: 0, output: '' });
  });

  it('slice done: cada símbolo do sot aparece no caminho linear', () => {
    const offPath = sotChanged((dir) => {
      edit(dir, MATRIX, (source) => source.replace('horizon: now · sot: [OrdersPage]', 'status: done · sot: [OrdersPage]'));
      edit(dir, ARCHITECTURE, (source) => source.replace(/1\. `apps\/app-web[^\n]*\n/, ''));
    });
    expect(offPath.status).toBe(1);
    expect(offPath.output).toContain('.metri/MATRIX.md:7: sot de S1: OrdersPage não está no Caminho linear do .metri/ARCHITECTURE.md');
    const planned = sotChanged((dir) => edit(dir, ARCHITECTURE, (source) => source.replace(/1\. `apps\/app-web[^\n]*\n/, '')));
    expect(planned).toEqual({ status: 0, output: '' });
  });

  it('cabeçalho antigo "// SOT:" é erro', () => {
    const { status, output } = sotChanged((dir) =>
      write(dir, 'packages/core/src/money.ts', `// SOT: Money, dinheiro em centavos
${header('Money')}export class Money {}
`),
    );
    expect(status).toBe(1);
    expect(output).toContain('packages/core/src/money.ts:1: cabeçalho: "SOT:" é o formato antigo');
  });

  it('kit de UI: só components/ui/ fica sem cabeçalho; hook e bloco da CLI são código do projeto', () => {
    const { status, output } = sotChanged((dir) => {
      write(dir, 'packages/ui/src/components/ui/button.tsx', 'export function Button() {\n  return null;\n}\n');
      write(dir, 'packages/ui/src/hooks/use-mobile.ts', 'export function useIsMobile() {\n  return false;\n}\n');
      write(dir, 'packages/ui/src/components/blocks/login-form.tsx', 'export function LoginForm() {\n  return null;\n}\n');
    });
    expect(status).toBe(1);
    expect(output).not.toContain('button.tsx');
    expect(output).toContain('packages/ui/src/hooks/use-mobile.ts:1: cabeçalho: arquivo-fonte sem SOURCE OF TRUTH');
    expect(output).toContain('packages/ui/src/components/blocks/login-form.tsx:1: cabeçalho: arquivo-fonte sem SOURCE OF TRUTH');
    expect(output).toContain('fora de components/ui/ é código do projeto');
  });

  it('caminho linear: cada passo com `arquivo:símbolo` que existe e tem cabeçalho', () => {
    const { status, output } = sotChanged((dir) =>
      edit(dir, ARCHITECTURE, (source) =>
        source.replace(
          '2. `apps/app-api',
          '2. a exportação legada.\n3. `apps/app-web/src/pages/orders/orders-page.tsx:OrderList` lista.\n4. `apps/app-web/src/nope.ts:Nope` some.\n5. `apps/app-api',
        ),
      ),
    );
    expect(status).toBe(1);
    expect(output).toContain('.metri/ARCHITECTURE.md:10: Caminho linear: passo sem `arquivo:símbolo`');
    expect(output).toContain(`.metri/ARCHITECTURE.md:11: Caminho linear: ${PAGE} não declara OrderList`);
    expect(output).toContain('.metri/ARCHITECTURE.md:12: Caminho linear: apps/app-web/src/nope.ts não existe ou não é arquivo-fonte');
    const unnamed = sotChanged((dir) =>
      edit(dir, PAGE, (source) => source.replace('SOURCE OF TRUTH: OrdersPage.', 'SOURCE OF TRUTH: the order list.')),
    );
    expect(unnamed.output).toContain(`Caminho linear: nenhum cabeçalho SOURCE OF TRUTH de ${PAGE} nomeia OrdersPage`);
  });

  it('arquivo sem export: sem cabeçalho, ou com ele acima da função do topo que o caminho linear nomeia', () => {
    const MAIN = 'apps/app-api/src/main.ts';
    const bootstrap = "async function bootstrap() {}\nbootstrap();\n";
    expect(sotChanged((dir) => write(dir, 'apps/app-web/src/main.tsx', "import './app';\ncreateRoot();\n"))).toEqual({ status: 0, output: '' });
    const named = sotChanged((dir) => {
      write(dir, MAIN, `import { NestFactory } from '@nestjs/core';\n\n${header('bootstrap')}${bootstrap}`);
      edit(dir, ARCHITECTURE, (source) => source.replace('2. `apps/app-api', `2. \`${MAIN}:bootstrap\` sobe o app.\n3. \`apps/app-api`));
    });
    expect(named).toEqual({ status: 0, output: '' });
  });

  it('cabeçalho: "generated" na prosa não isenta; /** num glob não abre comentário; CRLF vale', () => {
    const prose = sotChanged((dir) => write(dir, 'packages/core/src/unique-entity-id.ts', '// The entity id, generated by randomUUID.\nexport class UniqueEntityID {}\n'));
    expect(prose.output).toContain('packages/core/src/unique-entity-id.ts:1: cabeçalho: arquivo-fonte sem SOURCE OF TRUTH');
    const glob = sotChanged((dir) =>
      write(dir, 'apps/app-api/vitest.config.ts', `// Unit specs: \`src/**/*.spec.ts\`, no setup.\n${header('vitestConfig')}export const vitestConfig = {};\n`),
    );
    expect(glob).toEqual({ status: 0, output: '' });
    const crlf = sotChanged((dir) => write(dir, 'packages/core/src/money.ts', `${header('Money')}export class Money {}\n`.replace(/\n/g, '\r\n')));
    expect(crlf).toEqual({ status: 0, output: '' });
  });
});
