// Transitional text in the source: what tells the history of the method (a pilot, a version, a project's ticket) instead
// of the rule. Called by verify, only in the source; the CHANGELOG, which is the history, is outside the roots.
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, join } from 'node:path';

export type TransientProblem = { file: string; line: number; pattern: string; excerpt: string };

// Folders and files where the text is written for the agent or for the project: they say the rule in the present.
export const TRANSIENT_ROOTS = ['architecture', 'skills', 'agents', 'starter', 'cli/templates', 'README.md'];
const SKIPPED_DIRS = ['node_modules', '.turbo', '.vite', 'dist', 'coverage'];
// Generated by the package manager: versions are its content.
const SKIPPED_FILES = ['pnpm-lock.yaml'];
const TEXT_FILE = /\.(?:md|ts|tsx|js|mjs|cjs|json|yaml|yml|css|html|sh|example)$/;

const PATTERNS: { name: string; regex: RegExp }[] = [
  { name: 'piloto', regex: /\bpilot/i },
  { name: 'versão', regex: /(?<![\w.])v\d+\.\d+/ },
  { name: 'PP/GAP com número', regex: /\b(?:PP|GAP)-\d+\b/ },
  { name: 'id de ticket', regex: /\b(?:UC|T)\d+\.\d+\b/ },
];

// The two formats show a whole sample project (its tickets, gap and proposal): there, the ids are the sample.
const SAMPLE_PROJECT: Record<string, string[]> = {
  'skills/look-across/MATRIX-FORMAT.md': ['PP/GAP com número', 'id de ticket'],
  'skills/shape/SPEC-FORMAT.md': ['PP/GAP com número', 'id de ticket'],
};

function filesOf(root: string, path: string): string[] {
  const full = join(root, path);
  if (!existsSync(full)) {
    return [];
  }
  if (!statSync(full).isDirectory()) {
    return TEXT_FILE.test(path) && !SKIPPED_FILES.includes(basename(path)) ? [path] : [];
  }
  return readdirSync(full)
    .sort()
    .flatMap((name) => (SKIPPED_DIRS.includes(name) ? [] : filesOf(root, join(path, name))));
}

export function transientProblems(root: string): TransientProblem[] {
  const problems: TransientProblem[] = [];
  for (const file of TRANSIENT_ROOTS.flatMap((path) => filesOf(root, path))) {
    const lines = readFileSync(join(root, file), 'utf8').split('\n');
    lines.forEach((text, index) => {
      for (const { name, regex } of PATTERNS) {
        if (SAMPLE_PROJECT[file]?.includes(name)) {
          continue;
        }
        const found = regex.exec(text);
        if (found) {
          const from = Math.max(0, found.index - 20);
          problems.push({ file, line: index + 1, pattern: name, excerpt: text.slice(from, found.index + 40).trim() });
        }
      }
    });
  }
  return problems;
}
